### ISSUE TITLE
getVersion () method

### ISSUE THREAD

**Issue by mpd-dude** [arnaudleyder/radiant-medialyzer#2]
Hi Arnaud,
what do you think about adding a getVersion () method to the RadiantML which would return the current version string of the RadiantML library, e.g. "1.2.2."?

Best regards,
mpd-dude

**Comment by arnaudleyder** [comment]
Hi,

Sorry for my late answer I was away for a couple of days and I am just getting up to speed now. Implementing a getVersion() method should not be too complicated. However I am wondering what would be the production use case for that? Do you have any specific idea with this feature in mind?

Thanks
Arnaud

**Comment by arnaudleyder** [comment]
Added in [1.2.4](https://github.com/arnaudleyder/radiant-medialyzer/releases/tag/v1.2.4)
